# Generated by Django 4.2.6 on 2023-10-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
