# Generated by Django 4.2.6 on 2023-10-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_remove_details_address_line_alter_details_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='payment_amount',
            new_name='amount',
        ),
    ]
